# The ci-cd.yml file is used to define the Continuous Integration (CI) pipeline 
# for the project. It tells tools like GitHub Actions what steps to take automatically when you push changes to your code.

name: CI/CD Pipeline for Fullstack RAG Chatbot # This is the name of the pipeline which will appear in Github Actions Tab

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # This job will run on a GitHub VM with Ubuntu.

    steps:
    # Step 1: Checkout code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Simple echo step to see if the workflow is running
    - name: Hello World
      run: echo "Workflow is running"




